Application:
  Name: czx-app
  Int: 1
  Int32: 32
  Int64: 64
  Array:
    - 1
    - 2
    - 3

Database:
  Mysql:
    SlowThreshold: 5
    LogLevel: 4
    ConnMaxLifetime: 1
    MaxIdleConn: 2
    MaxOpenConn: 2
    ConnMaxIdleTime: 12
    Reade:
      - "root:root@tcp(192.168.0.180:3306)/test?charset=utf8mb4&loc=Local&parseTime=True"
    Write: "root:root@tcp(192.168.0.180:3306)/test?charset=utf8mb4&loc=Local&parseTime=True"

Redis:
  Disabled: false
  Addr: "192.168.0.180:6379"
  Pwd: ""
  Db: 0
  PoolSize: 20
  MaxIdleConn: 30
  MinIdleConn: 10
  # 单位（秒）
  MaxLifeTime: 60
  # 单位（分）
  MaxIdleTime: 30